INSERT INTO USER (NAME, EMAIL) VALUES ('davenkin', 'davenkin@gmail.com');
INSERT INTO USER (NAME, EMAIL) VALUES ('tom', 'tom@gmail.com');
INSERT INTO USER (NAME, EMAIL) VALUES ('kate', 'kate@gmail.com');

INSERT INTO CATEGORY (NAME) VALUES ('science');
INSERT INTO CATEGORY (NAME) VALUES ('economy');
INSERT INTO CATEGORY (NAME) VALUES ('culture');
INSERT INTO CATEGORY (NAME) VALUES ('politics');

INSERT INTO TAG (NAME) VALUES ('computer');
INSERT INTO TAG (NAME) VALUES ('programming');
INSERT INTO TAG (NAME) VALUES ('music');
INSERT INTO TAG (NAME) VALUES ('law');
INSERT INTO TAG (NAME) VALUES ('market');
INSERT INTO TAG (NAME) VALUES ('book');

INSERT INTO SURVEY(CONTENT,USER_ID, IS_MULTI_OPTIONS, CATEGORY_ID) VALUES(
'How many years have you been programming?',1,'N',1);

INSERT INTO SURVEY(CONTENT,USER_ID, IS_MULTI_OPTIONS, CATEGORY_ID) VALUES(
'How many books did you read last year?',2,'N',3);

INSERT INTO SURVEY(CONTENT,USER_ID, IS_MULTI_OPTIONS, CATEGORY_ID) VALUES(
'What kind of books do you like?',3,'Y',3);

INSERT INTO SURVEY(CONTENT,USER_ID, IS_MULTI_OPTIONS, CATEGORY_ID) VALUES(
'Who do you like best?',3,'N',4);

INSERT INTO SURVEY_TAG (SURVEY_ID, TAG_ID) VALUES (1,1);
INSERT INTO SURVEY_TAG (SURVEY_ID, TAG_ID) VALUES (1,2);
INSERT INTO SURVEY_TAG (SURVEY_ID, TAG_ID) VALUES (2,6);
INSERT INTO SURVEY_TAG (SURVEY_ID, TAG_ID) VALUES (3,6);


INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (1,'Less than 5 years');
INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (1,'5-10 years');
INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (1,'More than 10 years');


INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (2,'Less than 10');
INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (2,'More than 10');


INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (3,'Science fictions');
INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (3,'Love stories');
INSERT INTO SURVEY_OPTION_COUNT (SURVEY_ID, SURVEY_OPTION) VALUES (3,'History');



